Added initial command line arguments.
AttorneyOnline/acds pull request #1
Opened 2018-06-25 22:21 UTC by nnoodle

Should there be command line arguments?

2018-06-25 22:53 UTC, oldmud0 commented
It's not a top priority because nconf can already take configuration entries from argv. But I can see where it can be useful.

2018-06-26 03:23 UTC, oldmud0 requested changes

2018-06-26 03:23 UTC, oldmud0 commented on src/acds.js
> +let config = new Config(argv.config);
Changing only this declaration is not enough - there are more references to `Config`.

2018-06-26 06:08 UTC, nnoodle commented on src/acds.js
> +let config = new Config(argv.config);
Fixed by moving Config configuration to src/config.js

2018-06-27 15:03 UTC, merged